version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/app  # Mount code từ máy vào container để dev
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - MONGO_DETAILS=mongodb://mongodb:27017 # Ví dụ kết nối mongo local
    # Ghi đè lệnh CMD của Dockerfile để bật --reload và 1 worker duy nhất khi dev
    command: uvicorn src.main:combined_app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: